my:
   list:
       - name: 价格
         value: p
         options:
             "0-9999":  "不限"
             "0-5":  "5万以下"
             "5-8":  "5-8万"
             "8-12": "8-12万"
             "12-18": "12-18万"
             "18-25": "18-25万"
             "25-40": "25-40万"
             "40-80": "40-80万"
             "80-9999": "80万以上"
       - name: 级别
         value: l
         options:
              "0": "不限"
              "1": "轿车"
              "2": "微型车"
              "3": "小型车"
              "4": "紧凑型"
              "5": "中型车"
              "6": "中大型"
              "7": "豪华车"
              "8": "MPV"
              "9": "SUV"
              "10": "小型SUV"
              "11": "紧凑型SUV"
              "12": "中型SUV"
              "13": "中大型SUV"
              "14": "大型SUV"
              "15": "跑车"
              "16": "面包车"
              "17": "皮卡"
              "18": "客车"
              "19": "概念车"
              "20": "其它"
              "21": "卡车"
       - name: 国别
         value: c
         options:
             "0": "不限"
             "1": "德系"
             "2": "日系"
             "3": "韩系"
             "4": "美系"
             "5": "欧系"
             "6": "中国"
city:
   list:
       - name: 城市省份映射
         value: city
         options:
            "102": "1"
            "103": "1"
            "104": "1"
            "105": "1"
            "106": "1"
            "107": "1"
            "108": "1"
            "109": "1"
            "110": "1"
            "113": "1"
            "114": "1"
            "115": "1"
            "116": "1"
            "118": "1"
            "120": "1"
            "125": "1"
            "201": "2"
            "301": "3"
            "302": "3"
            "303": "3"
            "305": "3"
            "306": "3"
            "307": "3"
            "314": "3"
            "315": "3"
            "318": "3"
            "401": "4"
            "402": "4"
            "405": "4"
            "409": "4"
            "410": "4"
            "411": "4"
            "412": "4"
            "415": "4"
            "416": "4"
            "417": "4"
            "418": "4"
            "421": "4"
            "422": "4"
            "501": "5"
            "502": "5"
            "503": "5"
            "504": "5"
            "505": "5"
            "507": "5"
            "510": "5"
            "511": "5"
            "513": "5"
            "514": "5"
            "515": "5"
            "516": "5"
            "518": "5"
            "520": "5"
            "521": "5"
            "522": "5"
            "524": "5"
            "528": "5"
            "532": "5"
            "535": "5"
            "552": "5"
            "601": "6"
            "602": "6"
            "603": "6"
            "604": "6"
            "605": "6"
            "606": "6"
            "607": "6"
            "608": "6"
            "610": "6"
            "612": "6"
            "613": "6"
            "615": "6"
            "619": "6"
            "621": "6"
            "701": "7"
            "702": "7"
            "705": "7"
            "708": "7"
            "714": "7"
            "715": "7"
            "717": "7"
            "718": "7"
            "719": "7"
            "801": "8"
            "802": "8"
            "803": "8"
            "810": "8"
            "811": "8"
            "901": "9"
            "902": "9"
            "903": "9"
            "905": "9"
            "906": "9"
            "907": "9"
            "908": "9"
            "909": "9"
            "910": "9"
            "911": "9"
            "912": "9"
            "1001": "10"
            "1002": "10"
            "1003": "10"
            "1004": "10"
            "1005": "10"
            "1006": "10"
            "1007": "10"
            "1008": "10"
            "1009": "10"
            "1010": "10"
            "1011": "10"
            "1013": "10"
            "1014": "10"
            "1015": "21"
            "1016": "10"
            "1018": "10"
            "1019": "10"
            "1021": "10"
            "1023": "10"
            "1101": "11"
            "1102": "11"
            "1103": "11"
            "1104": "11"
            "1106": "11"
            "1107": "11"
            "1108": "11"
            "1109": "11"
            "1112": "11"
            "1113": "11"
            "1123": "11"
            "1131": "11"
            "1136": "11"
            "1201": "12"
            "1202": "12"
            "1203": "12"
            "1204": "12"
            "1205": "12"
            "1206": "12"
            "1207": "12"
            "1208": "12"
            "1209": "12"
            "1210": "12"
            "1216": "12"
            "1217": "12"
            "1219": "12"
            "1229": "12"
            "1236": "12"
            "1301": "13"
            "1302": "13"
            "1303": "13"
            "1304": "13"
            "1305": "13"
            "1306": "13"
            "1307": "13"
            "1308": "13"
            "1309": "13"
            "1310": "13"
            "1312": "13"
            "1313": "13"
            "1315": "13"
            "1333": "13"
            "1401": "14"
            "1402": "14"
            "1403": "14"
            "1405": "14"
            "1406": "14"
            "1412": "14"
            "1425": "14"
            "1428": "14"
            "1501": "15"
            "1502": "15"
            "1503": "15"
            "1505": "15"
            "1507": "15"
            "1510": "15"
            "1511": "15"
            "1512": "15"
            "1513": "15"
            "1515": "15"
            "1517": "15"
            "1518": "15"
            "1520": "15"
            "1601": "16"
            "1602": "16"
            "1603": "16"
            "1604": "16"
            "1605": "16"
            "1606": "16"
            "1607": "16"
            "1609": "16"
            "1612": "16"
            "1613": "16"
            "1615": "16"
            "1616": "14"
            "1701": "17"
            "1702": "17"
            "1703": "17"
            "1704": "17"
            "1705": "17"
            "1707": "17"
            "1708": "17"
            "1709": "17"
            "1710": "17"
            "1711": "17"
            "1713": "17"
            "1714": "17"
            "1716": "17"
            "1717": "17"
            "1801": "18"
            "1802": "18"
            "1803": "18"
            "1804": "18"
            "1805": "18"
            "1808": "18"
            "1812": "18"
            "1814": "18"
            "1824": "18"
            "1825": "18"
            "1829": "18"
            "1830": "18"
            "1901": "19"
            "1902": "19"
            "1903": "19"
            "1905": "19"
            "1907": "19"
            "2001": "20"
            "2023": "20"
            "2024": "20"
            "2025": "20"
            "2026": "20"
            "2027": "20"
            "2029": "20"
            "2030": "20"
            "2101": "21"
            "2102": "21"
            "2103": "21"
            "2104": "21"
            "2105": "21"
            "2106": "21"
            "2107": "21"
            "2109": "21"
            "2110": "21"
            "2112": "21"
            "2113": "21"
            "2114": "21"
            "2117": "21"
            "2118": "21"
            "2120": "21"
            "2126": "21"
            "2132": "21"
            "2201": "22"
            "2202": "22"
            "2203": "22"
            "2204": "22"
            "2205": "22"
            "2206": "22"
            "2207": "22"
            "2210": "22"
            "2218": "22"
            "2219": "22"
            "2227": "22"
            "2301": "23"
            "2302": "23"
            "2303": "23"
            "2304": "23"
            "2305": "23"
            "2306": "23"
            "2307": "23"
            "2308": "23"
            "2310": "23"
            "2313": "23"
            "2401": "24"
            "2501": "25"
            "2502": "25"
            "2503": "25"
            "2504": "25"
            "2506": "25"
            "2507": "25"
            "2508": "25"
            "2509": "25"
            "2510": "25"
            "2511": "25"
            "2512": "25"
            "2513": "25"
            "2514": "25"
            "2516": "25"
            "2517": "25"
            "2519": "25"
            "2530": "25"
            "2532": "25"
            "2535": "25"
            "2536": "25"
            "2537": "25"
            "2601": "26"
            "2701": "27"
            "2703": "27"
            "2704": "27"
            "2705": "27"
            "2707": "27"
            "2708": "27"
            "2709": "27"
            "2710": "27"
            "2801": "28"
            "2803": "28"
            "2810": "28"
            "2821": "28"
            "2822": "28"
            "2823": "28"
            "2828": "28"
            "2829": "28"
            "2830": "28"
            "2831": "28"
            "2832": "28"
            "2833": "28"
            "2834": "28"
            "2835": "28"
            "2901": "29"
            "2902": "29"
            "2903": "29"
            "2907": "29"
            "2911": "29"
            "2914": "29"
            "2915": "29"
            "2918": "29"
            "2922": "29"
            "2923": "29"
            "2925": "29"
            "2927": "29"
            "2928": "29"
            "2929": "29"
            "3001": "30"
            "3002": "30"
            "3003": "30"
            "3005": "30"
            "3006": "30"
            "3009": "30"
            "3011": "30"
            "3012": "30"
            "3015": "30"
            "3016": "30"
            "3020": "30"
            "3101": "31"
            "339000": "30"
            "339100": "30"
            "419000": "10"
            "422800": "12"
            "429000": "12"
            "469000": "8"
            "532300": "29"
            "532900": "29"
            "622900": "4"
            "652300": "28"
            "659000": "28"

